### ISSUE TITLE
The CM conf editor shows incorrect conf file content

### ISSUE THREAD

**Issue by afgane** [CloudVE/cloudman-ui#8]
`tool_conf.xml` was changed in the config map and the change is appropriately reflected on the container but the UI editor in CloudMan does not show the same content:

![Screen Shot 2020-01-10 at 5 09 34 PM](https://user-images.githubusercontent.com/338642/72189987-4c059280-33cc-11ea-9570-e7b930a04b67.png)

**Comment by nuwang** [comment]
As discussed, the editor will reflect changes through helm, but not direct config map edits.
